### ISSUE TITLE
Linux distros don't often come with curl

### ISSUE THREAD

**Issue by elena-pascal** [marcdegraef/EMsoft#1]
`sudo apt install curl`
alternativelly can use `wget` in the Build_SDK.sh

**Comment by imikejackson** [comment]
We are creating an EMsoft Superbuild repository that will use CMake to drive the entire SDK creation. Please give that a try at https://github.com/marcdegraef/EMsoftSuperbuild

This process is a bit different than running the shell script as it uses CMake. There should be some terse instructions somewhere in the repo. Please report any issues that you have with the Superbuild as issues on that repository.

Thanks
